name: Lint

on: 
  pull_request:
    branches:
      main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Add commands directory to PATH
        run: |
          echo "/HolismHolding/Commands" >> $GITHUB_PATH
      
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Lint with mypy
        run: |
          pip install mypy
          mypy .
          ...

      - name: Lint with isort
        run: |
          pip install isort
          isort .
          ...
      
      - name: Lint with black
        run: |
          pip install black
          black . --exclude="\.ipynb" .
          ...




      
